version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    environment:
      - ANDROID_NDK_HOME: ~/android-ndk
      - ANDROID_NDK_VERSION: r16b
    steps:
      - checkout

      # install android ndk
      - restore_cache:
          key: spokestack-android-ndk-{{ checksum "android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip" }}
      - run: wget -q -nc https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
      - run: if [ ! -d ${ANDROID_NDK_HOME} ]; then unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip -d ${ANDROID_NDK_HOME}
      - save_cache:
          paths:
            - ${ANDROID_NDK_HOME}
          key: spokestack-android-ndk-{{ checksum "android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip" }}

      # download dependencies
      - restore_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spokestack-android-{{ checksum "pom.xml" }}

      # build and verify
      - run: mvn -D$COVERALLS_REPO_TOKEN test jacoco:report coveralls:report
      - run: mvn checkstyle:check

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
