version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    environment:
      ANDROID_NDK_HOME: /home/circleci/android-ndk
      ANDROID_NDK_VERSION: r16b
    steps:
      - checkout

      # install android ndk
      - run: echo android-ndk-${ANDROID_NDK_VERSION} > /tmp/ndk-version
      - restore_cache:
          key: spokestack-android-ndk-{{ checksum "/tmp/ndk-version" }}
      - run: wget -q -nc https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
      - run: if [ ! -d $ANDROID_NDK_HOME ]; then mkdir $ANDROID_NDK_HOME && unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip -d $ANDROID_NDK_HOME; fi
      - save_cache:
          key: spokestack-android-ndk-{{ checksum "/tmp/ndk-version" }}
          paths:
            - android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
            - $ANDROID_NDK_HOME

      # download dependencies
      - restore_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      # build and verify
      - run: mvn -D$COVERALLS_REPO_TOKEN test jacoco:report coveralls:report
      - run: mvn checkstyle:check

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
