version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    environment:
      ANDROID_NDK_HOME: /home/circleci/android-ndk
      ANDROID_NDK_VERSION: r16b
    steps:
      - checkout
      - run:
          command: |
            git submodule sync &&
            git submodule update --init

      # install android ndk
      - run: sudo apt install build-essential
      - run: echo android-ndk-${ANDROID_NDK_VERSION}-1 > /tmp/ndk-version
      - restore_cache:
          key: spokestack-android-ndk-{{ checksum "/tmp/ndk-version" }}
      - run:
          command: |
            if [ ! -d $ANDROID_NDK_HOME ]; then
              wget -q -O /tmp/android-ndk.zip https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
              mkdir /tmp/android-ndk &&
              unzip -q /tmp/android-ndk.zip -d /tmp/android-ndk &&
              mv /tmp/android-ndk/android-ndk-${ANDROID_NDK_VERSION} $ANDROID_NDK_HOME ;
            fi
      - save_cache:
          key: spokestack-android-ndk-{{ checksum "/tmp/ndk-version" }}
          paths:
            - ~/android-ndk

      # download dependencies
      - restore_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      # build and verify
      - run: mvn -DrepoToken=${COVERALLS_REPO_TOKEN} test jacoco:report coveralls:report
      - run: mvn checkstyle:check

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
