version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    environment:
      - ANDROID_NDK_HOME: ~/android-ndk
      - ANDROID_NDK_VERSION: r16b

    steps:
      - checkout
      - run: wget -q https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
      - run: unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
      - run: mv ./android-ndk-${ANDROID_NDK_VERSION} ${ANDROID_NDK_HOME}
      - restore_cache:
          key: spokestack-android-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
            - ~/android-ndk
          key: spokestack-android-{{ checksum "pom.xml" }}
      - run: mvn -D$COVERALLS_REPO_TOKEN test jacoco:report coveralls:report
      - run: mvn checkstyle:check

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
