version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
      - image: bitriseio/android-ndk
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
