version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: bitriseio/android-ndk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: spokestack-android-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spokestack-android-{{ checksum "pom.xml" }}
      - run: mvn test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:

